config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Blazer::Engine, at: "blazer"
  root 'home#index'
  resources :home
  devise_for :users
  resources :quotes
  resources :interventions
  resources :machine_learning
  get 'intervention', to: 'interventions#index'
  get 'quote', to: 'quotes#new'
  get 'commercial', to: 'home#commercial'
  get 'residential', to: 'home#residential'
  get 'map', to: 'map#index'
  get 'dropbox/auth' => 'dropbox#auth'
  get 'dropbox/auth_callback' => 'dropbox#auth_callback'
  get 'machine_learning', to: 'machine_learning#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/quotes_controller.rb
require 'zendesk_main'

class QuotesController < ApplicationController
  before_action :authenticate_user!, :only => [:show]
  def new
    @quote = Quote.new
  end

  def index
    redirect_to main_app.root_path
  end

  
  def create
    @quote = Quote.new(quote_params)
    quote_price = @quote.price
    quote_elevator_needed = @quote.elevator_needed
    price_per_elevator = (quote_price.to_f / quote_elevator_needed.to_f)
    ZendeskAPI::Ticket.create!($client, :subject => "Task", :requester => { :name => @quote.company_name, :email => "rocketeam1234@gmail.com" }, :comment => { :body => "Subject: #{@quote.company_name}

      Comment: The company #{@quote.company_name} has made a quote for a #{@quote.building_type} building and wants the #{@quote.plan} service. 
      
      quote informations: 
      #{@quote.elevator_needed}
      #{price_per_elevator.round(2)}
      #{@quote.price}
      #{@quote.fees}
      #{@quote.total_price}
      
      The company #{@quote.company_name} can be reached at #{@quote.email}." }, :priority => "urgent")
      @quote.save
    redirect_to "#home"
  end

  def building_type
    @building_type = :building_type
  end

  private
  def quote_params
    params.require(:quote).permit(:email, :company_name, :building_type, :appartement, :floor, :basement, :plan, :business, :parking, :cages, :occupant, :elevator_needed, :price, :fees, :total_price)
  end
  

end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/index.html.erb
  <!-- wrapper -->
  <div id="wrapper">
    <!-- 
				AVAILABLE HEADER CLASSES

				Default nav height: 96px
				.header-md 		= 70px nav height
				.header-sm 		= 60px nav height

				.b-0 		= remove bottom border (only with transparent use)
				.sticky			= sticky header
				.static			= static header
				.dark			= dark header
				.bottom			= header on bottom
				
				shadow-before-1 = shadow 1 header top
				shadow-after-1 	= shadow 1 header bottom
				shadow-before-2 = shadow 2 header top
				shadow-after-2 	= shadow 2 header bottom
				shadow-before-3 = shadow 3 header top
				shadow-after-3 	= shadow 3 header bottom

				.clearfix		= required for mobile menu, do not remove!
			-->
    <div id="header" class="navbar-toggleable-md sticky header-md clearfix">
      <!-- TOP NAV -->
      <header id="topNav">
        <div class="container">
          <!-- Mobile Menu Button -->
          <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Logo -->
          <a class="logo float-left scrollTo" href="../../#home">
            <%= image_tag "/images/R2.png" %>
          </a>
          <!-- 
							Top Nav 
							
							AVAILABLE CLASSES:
							submenu-dark = dark sub menu
						-->
          <div class="
                navbar-collapse
                collapse
                float-right
                nav-main-collapse
                submenu-dark
              ">
            <nav class="nav-main">
              <!-- 
									.nav-onepage
									Required for onepage navigation links
									
									Add .external for an external link!
								-->
              <ul id="topMain" class="nav nav-pills nav-main nav-onepage">
                <li>
                  <!-- HOME -->
                  <a href="../../#home"> HOME </a>
                </li>
                <li>
                  <!-- SERVICES -->
                  <a href="../../#services"> SERVICES </a>
                </li>
                </li>
                <% if user_signed_in?%>
                  <% if current_user.admin == true || current_user.employee == true%>
                    <li>
                    <!-- AI -->
                      <a id="AI-nav" href="machine_learning"> AI </a>
                    </li>
                  <%end%>
                <% end %>
                <li>
                  <!-- WORK -->
                  <a href="../../#portfolio"> PORTFOLIO </a>
                </li>
                <li>
                  <!-- NEWS -->
                  <a href="../../#news"> NEWS </a>
                </li>
                <li>
                  <!-- CLIENTS -->
                  <a href="../../#clients"> CLIENTS </a>
                </li>
                <li>
                  <!-- CONTACT -->
                  <a href="../../#contact"> CONTACT </a>
                </li>
                <% if user_signed_in?%>
                  <% if current_user.admin == true || current_user.employee == true%>
                  <li>
                    <a class='navbar-link' href="/admin">ADMIN</a>
                  </li>
                  <%end%>
                <% end %>
                <% if user_signed_in? %>
                  <li>      
                    <%= link_to 'EDIT PROFILE' , edit_user_registration_path, :class=> 'navbar-link' %>
                  </li>                  
                  <li> 
                    <%= link_to "LOGOUT" , destroy_user_session_path, method: :delete, :class=> 'navbar-link' %>
                  </li>
                <% else %> 
                  <li>
                    <%= link_to "LOGIN" , new_user_session_path, :class=> 'navbar-link' %>
                  </li>
                  <li>
                    <%= link_to "SIGN UP" , new_user_registration_path, :class=> 'navbar-link' %>
                  </li> 
                <% end %>
              </ul>
            </nav>
          </div>
        </div>
      </header>
      <!-- /Top Nav -->
    </div>
<h1>Listing quotes</h1>
<%= link_to 'New quote', new_quote_path %>

 
<table>
  <tr>
    <th>Building type</th>
    <th>Number of appartement</th>
    <th>Number of floor</th>
    <th>Number of basement</th>
    <th>Plan Choosed</th>
    <th>Number of business</th>
    <th>Number of parking</th>
    <th>Number of cages</th>
    <th>Number of occupant</th>
    
    <th></th>
  </tr>
 
  <% @quotes.each do |quote| %>
    <tr>
      <td><%= quote.building_type %></td>
      <td><%= quote.appartement %></td>
      <td><%= quote.floor %></td>
      <td><%= quote.basement %></td>
      <td><%= quote.plan %></td>
      <td><%= quote.business %></td>
      <td><%= quote.parking %></td>
      <td><%= quote.cages %></td>
      <td><%= quote.occupant %></td>
      <td><%= link_to 'Show', quote_path(quote) %></td>
      <td><%= link_to 'Delete', quote_path(quote),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
                  <!-- FOOTER -->
                  <footer id="footer">
                    <div class="container">
                      <div class="row">
                        <!-- col #1 -->
                        <div class="col-md-8">
                          <h3 class="letter-spacing-1">WHY US?</h3>

                          <!-- Small Description -->
                          <p>
                            We have the conviction that we create the most innovative and
                            reliable products on the market. Contact us today for any
                            questions you might have.
                          </p>
                          <h2>(418) 555-1234</h2>
                        </div>
                        <!-- /col #1 -->

                        <!-- col #2 -->
                        <div class="col-md-4">
                          <h3 class="letter-spacing-1">KEEP IN TOUCH</h3>

                          <!-- Newsletter Form -->
                          <p>Subscribe to Our Newsletter to get Important News & Offers</p>

                          <form class="validate" action="" data-success="Subscribed! Thank you!"
                            data-toastr-position="bottom-right">
                            <div class="input-group">
                              <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                              <input type="email" id="email" name="email" class="form-control required"
                                placeholder="Enter your Email" />
                              <span class="input-group-btn">
                                <button class="btn btn-success" type="submit">
                                  Subscribe
                                </button>
                              </span>
                            </div>
                          </form>
                          <!-- /Newsletter Form -->
                        </div>
                        <!-- /col #2 -->
                      </div>
                    </div>

                    <div class="copyright">
                      <div class="container">
                        <ul class="float-right m-0 list-inline mobile-block">
                          <li><a href="#">Terms &amp; Conditions</a></li>
                          <li>&bull;</li>
                          <li><a href="#">Privacy</a></li>
                        </ul>
                        &copy; All Rights Reserved, Rocket Elevators
                      </div>
                    </div>
                  </footer>
                  <!-- /FOOTER -->
  </div>

app/views/quotes/new.html.erb
<head>
  <meta charset="utf-8" />
  <title>Rocket Elevator | Residential</title>
  <link rel="shortcut icon" href="assets/images/favicon.png" type="image/x-icon" />
  <meta name="description" content="" />
  <meta name="Author" content="Daniel Gallardo" />
   <script src="https://www.google.com/recaptcha/api.js"></script>
    <script>
   function onSubmit(token) {
     document.getElementById("demo-form").submit();}
 </script>
 <script src=<%="https://www.google.com/recaptcha/api.js?render=#{ENV['google_captcha']}"%>></script>


  <!-- mobile settings -->
  <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />
  <!--[if IE
      ]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"
    /><![endif]-->

  <!-- WEB FONTS : use %7C instead of | (pipe) -->
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700"
    rel="stylesheet" type="text/css" />
</head>

<!--
		AVAILABLE BODY CLASSES:
		
		smoothscroll 			= create a browser smooth scroll
		enable-animation		= enable WOW animations
	-->

<body class="enable-animation">
  <!-- wrapper -->
  <div id="wrapper">
    <!-- 
				AVAILABLE HEADER CLASSES

				Default nav height: 96px
				.header-md 		= 70px nav height
				.header-sm 		= 60px nav height

				.b-0 		= remove bottom border (only with transparent use)
				.sticky			= sticky header
				.static			= static header
				.dark			= dark header
				.bottom			= header on bottom
				
				shadow-before-1 = shadow 1 header top
				shadow-after-1 	= shadow 1 header bottom
				shadow-before-2 = shadow 2 header top
				shadow-after-2 	= shadow 2 header bottom
				shadow-before-3 = shadow 3 header top
				shadow-after-3 	= shadow 3 header bottom

				.clearfix		= required for mobile menu, do not remove!
			-->
    <div id="header" class="navbar-toggleable-md sticky header-md clearfix">
      <!-- TOP NAV -->
      <header id="topNav">
        <div class="container">
          <!-- Mobile Menu Button -->
          <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Logo -->
          <a class="logo float-left scrollTo" href="../../#home">
            <%= image_tag "/images/R2.png" %>
          </a>
          <!-- 
							Top Nav 
							
							AVAILABLE CLASSES:
							submenu-dark = dark sub menu
						-->
          <div class="
                navbar-collapse
                collapse
                float-right
                nav-main-collapse
                submenu-dark
              ">
            <nav class="nav-main">
              <!-- 
									.nav-onepage
									Required for onepage navigation links
									
									Add .external for an external link!
								-->
              <ul id="topMain" class="nav nav-pills nav-main nav-onepage">
                <li>
                  <!-- HOME -->
                  <a href="../../#home"> HOME </a>
                </li>
                <li>
                  <!-- SERVICES -->
                  <a href="../../#services"> SERVICES </a>
                </li>
                </li>
                <% if user_signed_in?%>
                  <% if current_user.admin == true || current_user.employee == true%>
                    <li>
                    <!-- AI -->
                      <a id="AI-nav" href="machine_learning"> AI </a>
                    </li>
                  <%end%>
                <% end %>
                <li>
                  <!-- WORK -->
                  <a href="../../#portfolio"> PORTFOLIO </a>
                </li>
                <li>
                  <!-- NEWS -->
                  <a href="../../#news"> NEWS </a>
                </li>
                <li>
                  <!-- CLIENTS -->
                  <a href="../../#clients"> CLIENTS </a>
                </li>
                <li>
                  <!-- CONTACT -->
                  <a href="../../#contact"> CONTACT </a>
                </li>
                <% if user_signed_in?%>
                  <% if current_user.admin == true || current_user.employee == true%>
                  <li>
                    <a class='navbar-link' href="/admin">ADMIN</a>
                  </li>
                  <%end%>
                <% end %>
                <% if user_signed_in? %>
                  <li>      
                    <%= link_to 'EDIT PROFILE' , edit_user_registration_path, :class=> 'navbar-link' %>
                  </li>                  
                  <li> 
                    <%= link_to "LOGOUT" , destroy_user_session_path, method: :delete, :class=> 'navbar-link' %>
                  </li>
                <% else %> 
                  <li>
                    <%= link_to "LOGIN" , new_user_session_path, :class=> 'navbar-link' %>
                  </li>
                  <li>
                    <%= link_to "SIGN UP" , new_user_registration_path, :class=> 'navbar-link' %>
                  </li> 
                <% end %>
              </ul>
            </nav>
          </div>
        </div>
      </header>
      <!-- /Top Nav -->
    </div>
    <div class="container">
    <h1>Submission Form</h1>


    <%= form_with scope: :quote, url: quotes_path, local: true do |form| %>

      <p>
        <%= form.label :email, :"Email *" %><br>
        <%= form.text_field :email, :required=> 'required' %>
      </p>

      <p>
        <%= form.label :company_name, :"Company Name *" %><br>
        <%= form.text_field :company_name, :required=> 'required' %>
      </p>

      <p onchange="getSelectValue()">
        <%= form.label :building_type %><br>
          <%= form.select :building_type, [["Select", "select" ], ["Residential", "residential" ],
            ["Commercial", "commercial" ], ["Corporate", "corporateHybrid" ], ["Hybrid", "corporateHybrid" ]] %>
      </p>
      <div id="floorBasement" style="display: none;">
        <p oninput="whichRadioButton()">
          <%= form.label :floor, :"Number of Floor :" %><br>
            <%= form.number_field :floor, min: 2, :required=> 'required' %>
        </p>


        <p oninput="whichRadioButton()">
          <%= form.label :basement, :"Number of Basement :" %><br>
            <%= form.number_field :basement, min: 0 , :required=> 'required'%>
        </p>
      </div>
      
      <%# Residential %>
        <div id="residential" style="display: none;">
          <p oninput="residential()">
            <%= form.label :appartement, :"Number of Appartement :" %><br>
              <%= form.number_field :appartement, min: 1%>
          </p>

        </div>
      
        <%# Commercial %>
          <div id="commercial" style="display: none;">
            <p oninput="commercial();">
              <%= form.label :business, :"Number of Businesses :" %><br>
                <%= form.number_field :business, min: 1%>
            </p>

            </p>
            <p oninput="commercial();">
              <%= form.label :parking, :"Number of Parking :" %><br>
                <%= form.number_field :parking , min: 1%>
            </p>


            <p oninput="commercial();">
              <%= form.label :cages, :"Number of Cage to be Deployed :" %><br>
                <%= form.number_field :cages , min: 1%>
            </p>
          </div>

          <%# Corporate and Hybrid %>

            <div id="corporateHybrid" style="display: none;">
              <p oninput="corporateHybrid1();">
                <%= form.label :business, :"Number of Businesses :" %><br>
                  <%= form.number_field :business , min: 1%>
              </p>

              </p>

              <p oninput="corporateHybrid1();">
                <%= form.label :parking, :"Number of Parking :" %><br>
                  <%= form.number_field :parking , min: 1%>
              </p>


              <p oninput="corporateHybrid1();">
                <%= form.label :occupant, :"Number of Occupant per Floor :" %><br>
                  <%= form.number_field :occupant , min: 1%>
              </p>
            </div>

            <%# Radio Button for Hybrid and Corporate %>
              <div id="radio_button" style="display: none;" onchange="whichRadioButton()">
                <p>
                  <%= form.radio_button :plan, 'standard', :required=> 'required' %>
                    <%= form.label :plan, 'Standard' , :value=> 'standard' %>
                      <%= form.radio_button :plan, 'premium' %>
                        <%= form.label :plan, 'Premium' , :value=> 'premium' %>
                          <%= form.radio_button :plan, 'excelium' %>
                            <%= form.label :plan, 'Excelium' , :value=> 'excelium' %>
                </p>

              </div>


              <%# Result %>
                <div id="result" style="display: none;">
                  <h2> Elevator Needed : <span id="elevatorNeeded"></span></h2>
                  <%= form.hidden_field :elevator_needed %>
                    <h2>Price per Cage :<span id="cageNeeded"></span>$</h2>
                    <%= form.hidden_field :cageNeeded %>
                      <h2>Elevator Price : <span id="price"> Price</span>$</h2>
                      <%= form.hidden_field :price %>
                        <h2>Installation Fees : <span id="fees"> Price</span>$</h2>
                        <%= form.hidden_field :fees %>
                          <h1>Total Price :<span id="totalPrice"></span>$</h1>
                          <%= form.hidden_field :total_price %>
                </div>

                <p style="display: none;" id="submitButton" onclick="alertbox()">
                  
                  <button class="g-recaptcha, btn btn-success btn-lg"  
                  data-sitekey=<%="#{ENV['google_captcha']}"%>
                  data-callback='onSubmit' 
                  data-action='submit'>Submit</button>
  </div>
                 
                    
                  
                  
                </p>
        <% end %>
            </div>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
                  <!-- FOOTER -->
                  <footer id="footer">
                    <div class="container">
                      <div class="row">
                        <!-- col #1 -->
                        <div class="col-md-8">
                          <h3 class="letter-spacing-1">WHY US?</h3>

                          <!-- Small Description -->
                          <p>
                            We have the conviction that we create the most innovative and
                            reliable products on the market. Contact us today for any
                            questions you might have.
                          </p>
                          <h2>(418) 555-1234</h2>
                        </div>
                        <!-- /col #1 -->

                        <!-- col #2 -->
                        <div class="col-md-4">
                          <h3 class="letter-spacing-1">KEEP IN TOUCH</h3>

                          <!-- Newsletter Form -->
                          <p>Subscribe to Our Newsletter to get Important News & Offers</p>

                          <form class="validate" action="" data-success="Subscribed! Thank you!"
                            data-toastr-position="bottom-right">
                            <div class="input-group">
                              <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                              <input type="email" id="email" name="email" class="form-control required"
                                placeholder="Enter your Email" />
                              <span class="input-group-btn">
                                <button class="btn btn-success" type="submit">
                                  Subscribe
                                </button>
                              </span>
                            </div>
                          </form>
                          <!-- /Newsletter Form -->
                        </div>
                        <!-- /col #2 -->
                      </div>
                    </div>

                    <div class="copyright">
                      <div class="container">
                        <ul class="float-right m-0 list-inline mobile-block">
                          <li><a href="#">Terms &amp; Conditions</a></li>
                          <li>&bull;</li>
                          <li><a href="#">Privacy</a></li>
                        </ul>
                        &copy; All Rights Reserved, Rocket Elevators
                      </div>
                    </div>
                  </footer>
                  <!-- /FOOTER -->
  </div>